version: '3.8'

services:
  mcp-proxy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MCP_URL=http://host.docker.internal:8005/sse
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_ALGORITHM=HS256
      - PORT=5000
      - DEBUG=false
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 